version: "2.4"

services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    cpus: 1.0
    mem_limit: 2g
    ports:
      - "25565:25565"
    volumes:
      - "data:/data"
      - "./src/main/js/lib:/server/scriptcraft/lib:ro"
      - "./src/main/js/modules:/server/scriptcraft/modules:ro"
      - "./src/main/js/plugins:/server/scriptcraft/plugins:ro"
      - "./target/scriptcraft.jar:/server/plugins/scriptcraft.jar:ro"
    # Without a TTY, Spigot consumes a lot of CPU when idle
    tty: true
    stdin_open: true

volumes:
  data:
